define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Screen1 generated by Appery.io
     * @module Screen1
     */

    APP.controller('Screen1', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            // On load screen logic
        };

        /**
         * user controller variables
         */
    }

});